name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    # Install .NET Framework
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.X
  
    # Restore and build server project
    - name: Restore dependencies - Server
      run: dotnet restore PersistentEmpiresServer/PersistentEmpiresServer.csproj
      working-directory: PersistentEmpiresServer

    - name: Build - Server
      run: dotnet build PersistentEmpiresServer/PersistentEmpiresServer.csproj --no-restore
      working-directory: PersistentEmpiresServer

    # Test server project
    - name: Test - Server
      run: dotnet test PersistentEmpiresServer/PersistentEmpiresServer.csproj --no-build --verbosity normal
      working-directory: PersistentEmpiresServer

    # Restore and build client project
    - name: Restore dependencies - Client
      run: dotnet restore PersistentEmpiresClient/PersistentEmpiresClient.csproj
      working-directory: PersistentEmpiresClient

    - name: Build - Client
      run: dotnet build PersistentEmpiresClient/PersistentEmpiresClient.csproj --no-restore
      working-directory: PersistentEmpiresClient

    # Test client project
    - name: Test - Client
      run: dotnet test PersistentEmpiresClient/PersistentEmpiresClient.csproj --no-build --verbosity normal
      working-directory: PersistentEmpiresClient

    # Restore and build harmony project
    - name: Restore dependencies - Harmony
      run: dotnet restore PersistentEmpiresHarmony/PersistentEmpiresHarmony.csproj
      working-directory: PersistentEmpiresHarmony

    - name: Build - Harmony
      run: dotnet build PersistentEmpiresHarmony/PersistentEmpiresHarmony.csproj --no-restore
      working-directory: PersistentEmpiresHarmony

    # Test harmony project
    - name: Test - Harmony
      run: dotnet test PersistentEmpiresHarmony/PersistentEmpiresHarmony.csproj --no-build --verbosity normal
      working-directory: PersistentEmpiresHarmony

    # Restore and build save project
    - name: Restore dependencies - Save
      run: dotnet restore PersistentEmpiresSave/PersistentEmpiresSave.csproj
      working-directory: PersistentEmpiresSave

    - name: Build - Save
      run: dotnet build PersistentEmpiresSave/PersistentEmpiresSave.csproj --no-restore
      working-directory: PersistentEmpiresSave

    # Test save project
    - name: Test - Save
      run: dotnet test PersistentEmpiresSave/PersistentEmpiresSave.csproj --no-build --verbosity normal
      working-directory: PersistentEmpiresSave
