#    Persistent Empires Open Sourced - A Mount and Blade: Bannerlord Mod
#    Copyright (C) 2024  Free Software Foundation, Inc.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: pe-build

on:
  workflow_call:
    inputs:
      build_project:
        description: "Whether to build Client or Server files"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      build_project:
        description: "Whether to build Client or Server files"
        required: true
        type: choice
        options:
        - Client
        - Server

env:
  SOLUTION_FILE_PATH: PersistentEmpires${{inputs.build_project}}/PersistentEmpires${{inputs.build_project}}.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    environment: development

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: dotnet publish -p:PublishProfile=${{inputs.build_project}}-win-x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Build Linux x64 Server
      run: dotnet publish -p:PublishProfile=${{inputs.build_project}}-linux-x64 ${{env.SOLUTION_FILE_PATH}}
      if: ${{inputs.build_project == 'Server'}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.build_project}}-Publish
        retention-days: 1
        path: 'publish'