name: pe-build

on:
  workflow_call:
    inputs:
      build_project:
        description: "Whether to build Client or Server files"
        required: true
        type: string
      build_configuration:
        description: "Whether to build Release or Debug"
        default: "Release"
        type: string
  workflow_dispatch:
    inputs:
      build_project:
        description: "Whether to build Client or Server files"
        required: true
        type: choice
        options:
        - Client
        - Server
      build_configuration:
        description: "Whether to build Release or Debug"
        default: "Release"
        type: choice
        options:
        - Release
        - Debug

env:
  SOLUTION_FILE_PATH: PersistentEmpires${{inputs.build_project}}/PersistentEmpires${{inputs.build_project}}.sln
  BUILD_CONFIGURATION: ${{inputs.build_configuration}}

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    environment: development

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: publish
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet publish -c ${{env.BUILD_CONFIGURATION}} -o ./publish ${{env.SOLUTION_FILE_PATH}}
      if: ${{inputs.build_project == 'Server'}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:build -restore -p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      if: ${{inputs.build_project == 'Client'}}


    - name: Upload server artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.build_project}}-${{inputs.build_configuration}}
        retention-days: 1
        path: 'publish'
      if: ${{inputs.build_project == 'Server'}}

    - name: Upload client artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.build_project}}-${{inputs.build_configuration}}
        retention-days: 1
        path: '**/bin/*/'
      if: ${{inputs.build_project == 'Client'}}