name: pe-deploy-staging

concurrency: staging

on:
  workflow_call:
  
jobs:  
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - uses: actions/checkout@v4
    - name: Calculate short sha
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Prepare working dirs
      run: |
        mkdir -p release/PersistentEmpiresClient
        mkdir -p release/PersistentEmpiresServer

    - name: Download Client build artifact
      uses: actions/download-artifact@v4
      with:
        name: Client-${{github.sha}}
        working-directory: release/PersistentEmpiresClient

    - name: Download Server build artifact
      uses: actions/download-artifact@v4
      with:
        name: Server-${{github.sha}}
        working-directory: release/PersistentEmpiresServer

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: rc-${{steps.vars.outputs.sha_short}}
        name: Prerelease ${{needs.tag-rc.outputs.new_tag}}
        prerelease: true
        token: ${{secrets.GITHUB_TOKEN}}
        artifacts: "release/PersistentEmpiresClient,release/PersistentEmpiresServer"