name: pe-deploy-production

concurrency: production

on:
  workflow_call:
  
jobs:
  tag-rc:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4
    - name: Tag release
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        custom_tag: ${{github.sha}}
        tag_prefix: release-
        github_token: ${{secrets.GITHUB_TOKEN}}

    outputs:
      new_tag : ${{steps.tag_version.outputs.new_tag}}
      changelog: ${{steps.tag_version.outputs.changelog}}
  
  deploy:
    runs-on: ubuntu-latest
    needs: tag-rc
    environment: production

    steps:
    - uses: actions/checkout@v4
    - name: Prepare working dirs
      run: |
        mkdir -p release/PersistentEmpiresClient
        mkdir -p release/PersistentEmpiresServer

    - name: Download Client build artifact
      uses: actions/download-artifact@v4
      with:
        name: Client-${{github.sha}}
        working-directory: release/PersistentEmpiresClient

    - name: Download Server build artifact
      uses: actions/download-artifact@v4
      with:
        name: Server-${{github.sha}}
        working-directory: release/PersistentEmpiresServer

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{needs.tag-rc.outputs.new_tag}}
        name: Release ${{needs.tag-rc.outputs.new_tag}}
        body: ${{needs.tag-rc.outputs.changelog}}
        token: ${{secrets.GITHUB_TOKEN}}
        artifacts: "release/PersistentEmpiresClient,release/PersistentEmpiresServer"