name: pe-deploy-production

concurrency: production

on:
  workflow_call:
  
jobs:  
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4
    - name: Prepare working dirs
      run: |
        mkdir -p release/PersistentEmpiresClient
        mkdir -p release/PersistentEmpiresServer

    - name: Download Client build artifact
      uses: actions/download-artifact@v4
      with:
        name: Client-${{github.sha}}
        working-directory: release/PersistentEmpiresClient

    - name: Download Server build artifact
      uses: actions/download-artifact@v4
      with:
        name: Server-${{github.sha}}
        working-directory: release/PersistentEmpiresServer

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{steps.vars.outputs.sha_short}}
        name: Release ${{needs.tag-rc.outputs.new_tag}}
        token: ${{secrets.GITHUB_TOKEN}}
        artifacts: "release/PersistentEmpiresClient,release/PersistentEmpiresServer"