#    Persistent Empires Open Sourced - A Mount and Blade: Bannerlord Mod
#    Copyright (C) 2024  Free Software Foundation, Inc.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: pe-deploy-production

concurrency: production

on:
  workflow_call:
  
jobs:  
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Calculate short sha
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "build_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Prepare working dirs
      run: |
        mkdir -p release/PersistentEmpiresClient
        mkdir -p release/PersistentEmpiresServer
    - name: Download Client build artifact
      uses: actions/download-artifact@v4
      with:
        name: Client-${{github.sha}}
        path: release/PersistentEmpiresClient
    - name: Clone client assets
      uses: actions/checkout@master
      with:
        repository: AR-Development/PersistentEmpires-Assets
        path: ClientAssets
    - name: Move Client assets without LFS
      run: |
        cp -arf ClientAssets/* release/PersistentEmpiresClient/Modules/PersistentEmpires/
        cp -arf ClientAssets/.git release/PersistentEmpiresClient/Modules/PersistentEmpires/.git
        cp -arf ClientAssets/.gitattributes release/PersistentEmpiresClient/Modules/PersistentEmpires/.gitattributes
        rm -rf ClientAssets
    - name: Download Server build artifact
      uses: actions/download-artifact@v4
      with:
        name: Server-${{github.sha}}
        path: release/PersistentEmpiresServer

    - name: Prepare working dirs
      run: |
        (cd release/PersistentEmpiresClient/ && zip -r ../../PersistentEmpiresClient.zip .)
        (cd release/PersistentEmpiresServer/ && zip -r ../../PersistentEmpiresServer.zip .)

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: release-${{steps.vars.outputs.build_date}}-${{steps.vars.outputs.sha_short}}
        name: Release ${{needs.tag-rc.outputs.new_tag}}
        token: ${{secrets.GITHUB_TOKEN}}
        artifacts: "PersistentEmpiresClient.zip,PersistentEmpiresServer.zip"