name: pe-lib-pipeline

on: [workflow_call, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./PersistentEmpiresLib

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - uses: nuget/setup-nuget@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore NuGet dependencies
      run: nuget restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal