name: pe-lint

on:
  workflow_call:
    inputs:
      build_project:
        description: "Whether to merge Client or Server files"
        required: true
        type: string
      build_configuration:
        description: "Whether to merge Release or Debug"
        default: "Release"
        type: string

jobs:
  merge-files:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.build_project}}-${{inputs.build_configuration}}

    - name: Merge Client Files
      run: |
        shopt -s globstar
        mkdir merged
        ls
        mv -f PersistentEmpiresClient/PersistentEmpiresClient/bin/${{inputs.build_configuration}}/*.dll merged/
      if: ${{inputs.build_project == 'Client'}}

    - name: Include ClientModFiles
      run: |
        shopt -s globstar
        mkdir ClientModFiles
        ls
        mv -f PersistentEmpiresClient/ClientModFiles/bin/${{inputs.build_configuration}}/* ClientModFiles/ 
      if: ${{inputs.build_project == 'Client'}}
    - name: Merge Server Files
      run: |
        shopt -s globstar
        mkdir merged
        ls
        cp -arf PersistentEmpiresLib/PersistentEmpiresLib/bin/${{inputs.build_configuration}}Server/*.dll merged/
        cp -arf PersistentEmpiresServer/*/bin/${{inputs.build_configuration}}/* merged/
      if: ${{inputs.build_project == 'Server'}}
    - name: Upload Client Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.build_project}}-Merged
        retention-days: 1
        path: |
          merged
          ClientModFiles
      if: ${{inputs.build_project == 'Client'}}
    - name: Upload Server Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.build_project}}-Merged
        retention-days: 1
        path: |
          merged
      if: ${{inputs.build_project == 'Server'}}