#    Persistent Empires Open Sourced - A Mount and Blade: Bannerlord Mod
#    Copyright (C) 2024  Free Software Foundation, Inc.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: pe-lint

on:
  workflow_call:
    inputs:
      build_project:
        description: "Whether to merge Client or Server files"
        required: true
        type: string
      build_configuration:
        description: "Whether to merge Release or Debug"
        default: "Release"
        type: string

jobs:
  merge-files:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.build_project}}-${{inputs.build_configuration}}

    - name: Merge files
      run: |
        shopt -s globstar
        rsync -ax --exclude GUI --exclude ClientModFiles.deps.json --exclude SubModule.xml **/bin/*/. merged

    - name: Include ClientModFiles
      run: |
        shopt -s globstar
        rsync -ax **/ClientModFiles/bin/*/. ClientModFiles
        # TODO: Add other client assets in this step, such as sounds, models, etc
      if: ${{inputs.build_project == 'Client'}}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.build_project}}-Merged
        retention-days: 1
        path: |
          merged
          ClientModFiles